name: Pull Request
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.29
  automerge:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot-preview[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

